import { Offer, Reservation, Review, Vendor, Voucher } from '@/types';

export const mockVendors: Vendor[] = [
  {
    id: 'v1',
    name: 'Bánh Mì Huỳnh Hoa',
    logo: 'fast-food-outline',
    logoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    address: '26 Lê Thị Riêng, Q1, HCMC',
    distance: 0.5,
    rating: 4.8,
    reviewCount: 234,
    trustScore: 4.8,
    latitude: 10.7769,
    longitude: 106.7009,
  },
  {
    id: 'v2',
    name: 'The Coffee House',
    logo: 'cafe-outline',
    logoUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    address: '86-88 Cao Thắng, Q3, HCMC',
    distance: 1.2,
    rating: 4.5,
    reviewCount: 156,
    trustScore: 4.6,
    latitude: 10.7823,
    longitude: 106.6917,
  },
  {
    id: 'v3',
    name: 'Phở Hòa Pasteur',
    logo: 'restaurant-outline',
    logoUrl: 'https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=400',
    address: '260C Pasteur, Q3, HCMC',
    distance: 0.8,
    rating: 4.7,
    reviewCount: 189,
    trustScore: 4.7,
    latitude: 10.7789,
    longitude: 106.6919,
  },
  {
    id: 'v4',
    name: 'Tous Les Jours',
    logo: 'storefront-outline',
    logoUrl: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=400',
    address: 'Vincom Center, Q1, HCMC',
    distance: 1.5,
    rating: 4.6,
    reviewCount: 98,
    trustScore: 4.5,
    latitude: 10.7797,
    longitude: 106.6991,
  },
  {
    id: 'v5',
    name: 'Green Bean Café',
    logo: 'cafe-outline',
    logoUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    address: '123 Nguyen Hue, District 1',
    distance: 0.4,
    rating: 4.8,
    reviewCount: 210,
    trustScore: 4.9,
    latitude: 10.7796,
    longitude: 106.6995,
  },
  {
    id: 'v6',
    name: 'Sunrise Bakery',
    logo: 'storefront-outline',
    logoUrl: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=400',
    address: '45 Le Loi, District 1',
    distance: 0.7,
    rating: 4.7,
    reviewCount: 180,
    trustScore: 4.8,
    latitude: 10.7758,
    longitude: 106.7017,
  },
  {
    id: 'v7',
    name: 'Pho Paradise',
    logo: 'restaurant-outline',
    logoUrl: 'https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=400',
    address: '789 Dong Khoi, District 1',
    distance: 1.0,
    rating: 4.9,
    reviewCount: 260,
    trustScore: 4.9,
    latitude: 10.7821,
    longitude: 106.6954,
  },
  {
    id: 'v8',
    name: 'Fresh Market',
    logo: 'cart-outline',
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    address: '15 Ham Nghi, District 1',
    distance: 0.9,
    rating: 4.5,
    reviewCount: 140,
    trustScore: 4.6,
    latitude: 10.7778,
    longitude: 106.6956,
  },
];

export const mockVouchers: Voucher[] = [
  {
    id: 'vch1',
    code: 'SAVE10K',
    title: 'Giảm 10k',
    description: 'Giảm 10.000₫ cho đơn hàng từ 30.000₫',
    discountType: 'fixed',
    amount: 10_000,
    minOrder: 30_000,
    isActive: true,
  },
  {
    id: 'vch2',
    code: 'SAVE20',
    title: 'Giảm 20%',
    description: 'Giảm 20% (tối đa 15.000₫) cho đơn hàng từ 50.000₫',
    discountType: 'percent',
    amount: 20,
    maxDiscount: 15_000,
    minOrder: 50_000,
    isActive: true,
  },
  {
    id: 'vch3',
    code: 'FREESHIP5K',
    title: 'Thưởng 5k',
    description: 'Giảm 5.000₫ cho mọi đơn hàng',
    discountType: 'fixed',
    amount: 5_000,
    isActive: true,
  },
];

export const mockOffers: Offer[] = [
  // EXPIRED BAG - ended at 18:00 today (should NOT show after 18:00)
  {
    id: 'o1',
    vendorId: 'v1',
    vendor: mockVendors[0],
    title: 'Túi Bánh Mì Bất Ngờ',
    description: 'Bánh mì hỗn hợp từ hôm nay - có thể bao gồm pâté, thịt nướng hoặc gà',
    price: 25000,
    originalValue: 60000,
    quantity: 10,
    remainingQuantity: 3,
    collectionStart: (() => {
      const d = new Date();
      d.setHours(22, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionEnd: (() => {
      const d = new Date();
      d.setHours(24, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    bagSize: 'Small',
    dietaryTags: ['Meat'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
    isActive: true,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago - NEW
  },
  // AVAILABLE - ends at 23:00 today (shows until 23:00)
  {
    id: 'o2',
    vendorId: 'v2',
    vendor: mockVendors[1],
    title: 'Combo Cà Phê & Bánh Ngọt',
    description: 'Bánh ngọt cuối ngày với đồ uống tùy chọn',
    price: 35000,
    originalValue: 85000,
    quantity: 5,
    remainingQuantity: 5,
    collectionStart: (() => {
      const d = new Date();
      d.setHours(17, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionEnd: (() => {
      const d = new Date();
      d.setHours(23, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    bagSize: 'Medium',
    dietaryTags: ['Vegetarian'],
    foodType: 'Drinks',
    photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800'],
    isActive: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago - NEW
  },
  // AVAILABLE - ends at 22:00 today (shows until 22:00)
  {
    id: 'o3',
    vendorId: 'v3',
    vendor: mockVendors[2],
    title: 'Tô Phở Bất Ngờ',
    description: 'Phở tươi với lựa chọn thịt - bò hoặc gà',
    price: 40000,
    originalValue: 80000,
    quantity: 8,
    remainingQuantity: 8,
    collectionStart: (() => {
      const d = new Date();
      d.setHours(18, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionEnd: (() => {
      const d = new Date();
      d.setHours(22, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    bagSize: 'Medium',
    dietaryTags: ['Meat'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  // WEEKENDS ONLY - 10:00-14:00 (shows only Sat/Sun before 14:00)
  {
    id: 'o4',
    vendorId: 'v4',
    vendor: mockVendors[3],
    title: 'Hộp Bánh Bất Ngờ',
    description: 'Hỗn hợp bánh sừng bò, bánh danish và bánh mì từ hôm nay',
    price: 50000,
    originalValue: 120000,
    quantity: 15,
    remainingQuantity: 12,
    collectionStart: (() => {
      const d = new Date();
      d.setHours(10, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionEnd: (() => {
      const d = new Date();
      d.setHours(14, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionDays: ['Saturday', 'Sunday'],
    bagSize: 'Large',
    dietaryTags: ['Vegetarian'],
    foodType: 'Pastries',
    photos: ['https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  // Vendor v1 additional offers
  {
    id: 'o5',
    vendorId: 'v1',
    vendor: mockVendors[0],
    title: 'Gói Gỏi Cuốn Việt Nam',
    description: 'Gỏi cuốn tươi với tôm và thịt heo, ăn kèm nước chấm đậu phộng',
    price: 30000,
    originalValue: 65000,
    quantity: 8,
    remainingQuantity: 6,
    collectionStart: (() => {
      const d = new Date();
      d.setHours(15, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionEnd: (() => {
      const d = new Date();
      d.setHours(24, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionDays: ['Monday','Tuesday', 'Thursday', 'Saturday', 'Sunday'],
    bagSize: 'Small',
    dietaryTags: ['Meat'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o6',
    vendorId: 'v1',
    vendor: mockVendors[0],
    title: 'Bánh Mì Chay Đặc Biệt',
    description: 'Bánh mì đậu hũ và rau củ với nước sốt đặc biệt của nhà hàng',
    price: 20000,
    originalValue: 45000,
    quantity: 12,
    remainingQuantity: 10,
    collectionStart: (() => {
      const d = new Date();
      d.setHours(11, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionEnd: (() => {
      const d = new Date();
      d.setHours(15, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    bagSize: 'Small',
    dietaryTags: ['Vegetarian', 'Vegan'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  // EXPIRED - ended at 17:00 today
  {
    id: 'o7',
    vendorId: 'v1',
    vendor: mockVendors[0],
    title: 'Cơm Tấm Thịt Nướng',
    description: 'Cơm tấm với thịt heo nướng, trứng và rau củ ngâm chua',
    price: 35000,
    originalValue: 70000,
    quantity: 6,
    remainingQuantity: 4,
    collectionStart: (() => {
      const d = new Date();
      d.setHours(12, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionEnd: (() => {
      const d = new Date();
      d.setHours(17, 0, 0, 0);
      return d.toISOString();
    })(),
    collectionDays: ['Monday', 'Wednesday', 'Friday'],
    bagSize: 'Medium',
    dietaryTags: ['Meat'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  // Additional offers for other vendors
  {
    id: 'o8',
    vendorId: 'v2',
    vendor: mockVendors[1],
    title: 'Túi Cà Phê & Snack Chiều',
    description: 'Cà phê đá, trà và hỗn hợp bánh ngọt từ giờ cao điểm chiều.',
    price: 30000,
    originalValue: 90000,
    quantity: 6,
    remainingQuantity: 6,
    collectionStart: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    collectionEnd: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    collectionDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    bagSize: 'Small',
    dietaryTags: ['Vegetarian'],
    foodType: 'Drinks',
    photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o9',
    vendorId: 'v3',
    vendor: mockVendors[2],
    title: 'Gói Phở Gia Đình',
    description: 'Phần lớn phở bò và gà với rau thơm tươi và món ăn kèm.',
    price: 70000,
    originalValue: 200000,
    quantity: 4,
    remainingQuantity: 4,
    collectionStart: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    collectionEnd: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
    collectionDays: ['Friday', 'Saturday', 'Sunday'],
    bagSize: 'Large',
    dietaryTags: ['Meat'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o10',
    vendorId: 'v4',
    vendor: mockVendors[3],
    title: 'Sweet Treats Evening Box',
    description: 'Cakes, tarts and macarons that didn’t sell during the day.',
    price: 45000,
    originalValue: 135000,
    quantity: 5,
    remainingQuantity: 5,
    collectionStart: new Date(Date.now() + 19 * 60 * 60 * 1000).toISOString(),
    collectionEnd: new Date(Date.now() + 21 * 60 * 60 * 1000).toISOString(),
    collectionDays: ['Friday', 'Saturday'],
    bagSize: 'Medium',
    dietaryTags: ['Vegetarian'],
    foodType: 'Pastries',
    photos: ['https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o11',
    vendorId: 'v5',
    vendor: mockVendors[4],
    title: 'Túi Bữa Sáng Bất Ngờ',
    description: 'Bánh ngọt tươi, sandwich và đồ uống cà phê đặc biệt.',
    price: 50000,
    originalValue: 150000,
    quantity: 5,
    remainingQuantity: 5,
    collectionStart: new Date(Date.now() + 7.5 * 60 * 60 * 1000).toISOString(),
    collectionEnd: new Date(Date.now() + 9 * 60 * 60 * 1000).toISOString(),
    collectionDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    bagSize: 'Medium',
    dietaryTags: ['Vegetarian'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o12',
    vendorId: 'v5',
    vendor: mockVendors[4],
    title: 'Hộp Café Chiều',
    description: 'Cà phê pha lạnh, trà đá và bánh còn lại từ trong ngày.',
    price: 40000,
    originalValue: 120000,
    quantity: 4,
    remainingQuantity: 4,
    collectionStart: new Date(Date.now() + 15 * 60 * 60 * 1000).toISOString(),
    collectionEnd: new Date(Date.now() + 17 * 60 * 60 * 1000).toISOString(),
    collectionDays: ['Monday', 'Wednesday', 'Friday'],
    bagSize: 'Small',
    dietaryTags: ['Vegetarian'],
    foodType: 'Drinks',
    photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o13',
    vendorId: 'v6',
    vendor: mockVendors[5],
    title: 'Túi Bánh Mì Buổi Sáng',
    description: 'Bánh sừng bò, bánh bao và bánh mì hỗn hợp từ lò nướng sáng.',
    price: 38000,
    originalValue: 110000,
    quantity: 6,
    remainingQuantity: 6,
    collectionStart: new Date(Date.now() + 6.5 * 60 * 60 * 1000).toISOString(),
    collectionEnd: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    collectionDays: ['Monday', 'Tuesday', 'Thursday', 'Saturday'],
    bagSize: 'Large',
    dietaryTags: ['Vegetarian'],
    foodType: 'Pastries',
    photos: ['https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o14',
    vendorId: 'v6',
    vendor: mockVendors[5],
    title: 'Hộp Bánh Ngọt Tối',
    description: 'Bánh kem, bánh quy và bánh mì ngọt còn lại từ tủ trưng bày.',
    price: 36000,
    originalValue: 100000,
    quantity: 5,
    remainingQuantity: 5,
    collectionStart: (() => {
      const d = new Date();
      d.setHours(18, 55, 0, 0);
      return d.toISOString();
    })(),
    collectionEnd: (() => {
      const d = new Date();
      d.setHours(20, 55, 0, 0);
      return d.toISOString();
    })(),
    collectionDays: ['Friday', 'Saturday', 'Sunday'],
    bagSize: 'Medium',
    dietaryTags: ['Vegetarian'],
    foodType: 'Pastries',
    photos: ['https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o15',
    vendorId: 'v7',
    vendor: mockVendors[6],
    title: 'Món Ăn Đường Phố Yêu Thích',
    description: 'Lựa chọn các món Việt Nam: phở, gỏi cuốn và cơm.',
    price: 60000,
    originalValue: 180000,
    quantity: 3,
    remainingQuantity: 3,
    collectionStart: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    collectionEnd: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
    collectionDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    bagSize: 'Large',
    dietaryTags: ['Meat'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o16',
    vendorId: 'v8',
    vendor: mockVendors[7],
    title: 'Rau Củ Tươi Bất Ngờ',
    description: 'Trái cây và rau củ theo mùa còn tốt nhưng gần hết hạn.',
    price: 35000,
    originalValue: 100000,
    quantity: 7,
    remainingQuantity: 7,
    collectionStart: new Date(Date.now() + 17 * 60 * 60 * 1000).toISOString(),
    collectionEnd: new Date(Date.now() + 19 * 60 * 60 * 1000).toISOString(),
    collectionDays: ['Monday', 'Wednesday', 'Friday'],
    bagSize: 'Medium',
    dietaryTags: ['Vegan', 'Vegetarian'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1542838132-92c53300491e?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'o17',
    vendorId: 'v8',
    vendor: mockVendors[7],
    title: 'Hộp Tạp Hóa Thiết Yếu',
    description: 'Hàng khô, đồ ăn vặt và thực phẩm tủ mà siêu thị sẽ lãng phí.',
    price: 32000,
    originalValue: 90000,
    quantity: 6,
    remainingQuantity: 6,
    collectionStart: new Date(Date.now() + 16 * 60 * 60 * 1000).toISOString(),
    collectionEnd: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    collectionDays: ['Tuesday', 'Thursday', 'Saturday'],
    bagSize: 'Large',
    dietaryTags: ['Vegan'],
    foodType: 'Meals',
    photos: ['https://images.unsplash.com/photo-1542838132-92c53300491e?w=800'],
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const mockReservations: Reservation[] = [
  // Ongoing order
  {
    id: 'res1',
    code: 'ABC123',
    offerId: 'o2',
    offer: {
      id: 'o2',
      vendorId: 'v2',
      vendor: mockVendors[1],
      title: 'Coffee & Pastry Combo',
      description: 'End of day pastries with a drink of your choice',
      price: 35000,
      originalValue: 85000,
      quantity: 5,
      remainingQuantity: 5,
      collectionStart: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
      collectionEnd: new Date(Date.now() + 7 * 60 * 60 * 1000).toISOString(),
      collectionDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      bagSize: 'Medium',
      dietaryTags: ['Vegetarian'],
      foodType: 'Drinks',
      photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800'],
      isActive: true,
      createdAt: new Date().toISOString(),
    },
    userId: 'u1',
    status: 'Reserved',
    quantity: 2,
    collectionDate: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    collectionTimeStart: new Date(Date.now() + 5 * 60 * 60 * 1000).toISOString(),
    collectionTimeEnd: new Date(Date.now() + 7 * 60 * 60 * 1000).toISOString(),
    reservedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    paidPrice: 70000,
  },
  // Completed orders
  {
    id: 'res2',
    code: 'XYZ789',
    offerId: 'o1',
    offer: {
      id: 'o1',
      vendorId: 'v1',
      vendor: mockVendors[0],
      title: 'Surprise Bánh Mì Bag',
      description: 'Assorted bánh mì from today - could include pâté, grilled pork, or chicken',
      price: 25000,
      originalValue: 60000,
      quantity: 10,
      remainingQuantity: 3,
      collectionStart: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      collectionEnd: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
      collectionDays: ['Monday', 'Wednesday', 'Friday'],
      bagSize: 'Small',
      dietaryTags: ['Meat'],
      foodType: 'Meals',
      photos: ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
      isActive: true,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    userId: 'u1',
    status: 'Collected',
    quantity: 3,
    collectionDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    collectionTimeStart: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    collectionTimeEnd: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    reservedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 60 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000).toISOString(),
    paidPrice: 75000,
  },
  {
    id: 'res3',
    code: 'DEF456',
    offerId: 'o3',
    offer: {
      id: 'o3',
      vendorId: 'v3',
      vendor: mockVendors[2],
      title: 'Phở Surprise Bowl',
      description: 'Fresh phở with your choice of protein - beef or chicken',
      price: 40000,
      originalValue: 80000,
      quantity: 8,
      remainingQuantity: 8,
      collectionStart: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      collectionEnd: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
      collectionDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      bagSize: 'Medium',
      dietaryTags: ['Meat'],
      foodType: 'Meals',
      photos: ['https://images.unsplash.com/photo-1555992336-fb0d29498b13?w=800'],
      isActive: true,
      createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    },
    userId: 'u1',
    status: 'Collected',
    quantity: 1,
    collectionDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    collectionTimeStart: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    collectionTimeEnd: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    reservedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
    paidPrice: 40000,
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    offerId: 'o1',
    userId: 'u1',
    userName: 'Nguyen Van A',
    reservationId: 'res2',
    rating: 5.0,
    collectionRating: 5,
    qualityRating: 5,
    quantityRating: 5,
    varietyRating: 5,
    text: 'Giá trị tuyệt vời! Có 3 bánh mì ngon. Tươi và ngon!',
    photos: [],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r2',
    offerId: 'o2',
    userId: 'u2',
    userName: 'Tran Thi B',
    rating: 4.5,
    collectionRating: 5,
    qualityRating: 4,
    quantityRating: 5,
    varietyRating: 4,
    text: 'Cà phê và bánh ngọt tuyệt vời. Tiết kiệm tiền và giảm lãng phí!',
    photos: [],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r3',
    offerId: 'o1',
    userId: 'u3',
    userName: 'Le Van C',
    rating: 4.0,
    collectionRating: 4,
    qualityRating: 4,
    quantityRating: 4,
    varietyRating: 4,
    text: 'Lựa chọn tốt, nhận hàng nhanh và dễ dàng.',
    photos: [],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r6',
    offerId: 'o3',
    userId: 'u1',
    userName: 'Nguyen Van A',
    reservationId: 'res3',
    rating: 4.5,
    collectionRating: 5,
    qualityRating: 4,
    quantityRating: 4,
    varietyRating: 5,
    text: 'Phở ngon! Phần ăn lớn và nguyên liệu rất tươi.',
    photos: [],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r4',
    offerId: 'o3',
    userId: 'u4',
    userName: 'Pham Thi D',
    rating: 5.0,
    collectionRating: 5,
    qualityRating: 5,
    quantityRating: 5,
    varietyRating: 5,
    text: 'Phở ngon! Phần ăn lớn và rất tươi.',
    photos: [],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'r5',
    offerId: 'o4',
    userId: 'u5',
    userName: 'Hoang Van E',
    rating: 4.5,
    collectionRating: 5,
    qualityRating: 5,
    quantityRating: 4,
    varietyRating: 4,
    text: 'Bánh ngọt tuyệt vời. Chắc chắn sẽ đặt lại!',
    photos: [],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
